### Get all books
GET http://localhost:5000/books
Accept: */*
Cache-Control: no-cache
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1Nzk1OTA0OTgsImlhdCI6MTU3OTU4OTI5OCwic3ViIjoiYWZ6YWwifQ.tsB9sFqqkQpgk3yZg-7fY5kJhf9MKDjo_pruggwfjOY

### Get book by isbn
GET http://localhost:5000/books/12346
Accept: */*
Cache-Control: no-cache
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1Nzk1OTA0OTgsImlhdCI6MTU3OTU4OTI5OCwic3ViIjoiYWZ6YWwifQ.tsB9sFqqkQpgk3yZg-7fY5kJhf9MKDjo_pruggwfjOY
### Add a new book

POST http://localhost:5000/books
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "name": "Harry Potter",
  "price": 99.9,
  "isbn": 1234567
}

### Invalid POST request -1

POST http://localhost:5000/books
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "name": "Harry Potter",
  "price": 99.9,
  "isbnx": 1234567
}



### Book Update PUT

PUT http://localhost:5000/books/1234567
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "name": "ABC",
  "price": 99.9
}

###

PATCH http://localhost:5000/books/1234567
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "price": 199.9
}

### Delete the book
DELETE http://localhost:5000/books/1234567
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

### Login
POST http://localhost:5000/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "username": "afzal",
  "password": "pwdtest"
}

###